[workspace]
members = ["vnt","common","vnt-cli","vnt-jni"]
resolver = "2"

[profile.release]
opt-level = 'z'
debug = 0
debug-assertions = false
strip= "debuginfo"
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false
